name: Build Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Expo Prebuild
        run: npx expo prebuild --platform android --clean

      - name: Build Unsigned Release APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Sign APK with Debug Keystore
        working-directory: android
        run: |
          BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
          $BUILD_TOOLS_DIR/apksigner sign --ks app/debug.keystore --ks-pass pass:android --key-pass pass:android --ks-key-name androiddebugkey app/build/outputs/apk/release/app-release-unsigned.apk
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/mushaf-qiyam.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mushaf-qiyam-apk
          path: android/app/build/outputs/apk/release/mushaf-qiyam.apk

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "android/app/build/outputs/apk/release/mushaf-qiyam.apk"
          tag: "latest-release"
          name: "Mushaf Qiyam APK Release"
          body: "Auto-generated Mushaf Qiyam APK."
          allowUpdates: true
          makeLatest: true
